Lesson3
UkhanovKirill/Django pull request #3
Opened 2022-02-16 18:00 UTC by UkhanovKirill

2022-02-16 20:22 UTC, Vokler requested changes
Не совсем понял, что вы имели в виду насчет ошибки в namespace - можете привести пример?

Насчет `app_name` - если вы не добавите это, то урл адреса не будут работать

2022-02-16 20:22 UTC, Vokler commented on products/views.py
> +    file_path = settings.BASE_DIR / 'products/fixtures/goods.json'
file_path - больше не нужен вроде или у вас где-то используется?

2022-02-16 21:43 UTC, UkhanovKirill commented on products/views.py
> +    file_path = settings.BASE_DIR / 'products/fixtures/goods.json'
я для себя доделал второй урок

2022-02-16 22:02 UTC, UkhanovKirill commented on products/views.py
> +    file_path = settings.BASE_DIR / 'products/fixtures/goods.json'
> Не совсем понял, что вы должны увидеть на счет ошибок в пространстве имен - можно представить пример?

Я написал namespase, и выдавала ошибку 'команда не распознана', я не сразу заметил грамматическую ошибку, ну и методом тыка наткнулся на то что всё работает и без этой переменной

> Насчет `app_name`- если вы не добавите это, то урл адреса не будут работать

Это я понял. Так же примером: вместо 'products' я написал 'produts', и всё работало. Вообще чтобы я не написал на работу программы это не влияло. Вот и вопрос, эта переменная где-то будет фигурировать или вы об этом еще расскажете?

2022-02-17 08:22 UTC, Vokler commented on products/views.py
> +    file_path = settings.BASE_DIR / 'products/fixtures/goods.json'
Если мы указываем namespace, то app_name долежн быть обязательно для того, чтобы Django понял, к какому приложению относится URL диспетчер.

Но можно namespace не указывать, а оставить просто `app_name` и тогда все будет работать так же как и с namespace.

Здесь поднимался данный вопрос и там достаточно хорошо описан пример
https://stackoverflow.com/questions/61254816/what-is-the-purpose-of-app-name-in-urls-py-in-django

2022-02-17 08:23 UTC, Vokler approved these changes

2022-02-17 08:23 UTC, merged